name: "Attachment: ICS calendar file with suspicious application identifier"
description: "Flags messages containing ICS calendar file attachments whose parsed PRODID field contains a suspicious non-standard application identifier."
type: "rule"
severity: "high"
source: |
  type.inbound
  and any(attachments,
          (
            .file_type == "ics"
            or (
              .file_extension == "ics"
              or .content_type in ("application/ics", "text/calendar")
            )
          )
          //
          // This rule makes use of a beta feature and is subject to change without notice
          // using the beta feature in custom rules is not suggested until it has been formally released
          //
          and strings.icontains(beta.file.parse_ics(.).product_id, "-//My App")
  )
attack_types:
  - "ICS Phishing"
tactics_and_techniques:
  - "Social engineering"
  - "Evasion"
detection_methods:
  - "File analysis"
  - "Content analysis"
id: "a4d9122a-3468-5683-a40c-ff15e0818a2f"
og_id: "35566008-d9be-5e48-bd42-b8920c946110"
testing_pr: 4797
testing_sha: a43557136851c674ed33e0c1320379e35537e5b3