rule malicious_docx_document_template_artifacts {
	meta:
		author      = "kyle eaton"
		date        = "2026-06-17"
		description = "Matching some of the artifacts from a malicious docx document.xml file"
	strings:
		$builder = "<!-- Generated by Aspose.Words for Python"
		$s1      = "OneDrive Notification"
		$s2      = "Microsoft Cloud Services"
		$s3      = "Document Ready For Review"
	condition:
		$builder and any of ($s*)
}