name: MQL Mimic Tests

on:
  push:
    branches: [ "**" ]

concurrency:
  # For pull_request_target workflows we want to use head_ref -- the branch triggering the workflow. Otherwise,
  # use ref, which is the branch for a push event.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-via-zapier:
    name: Trigger Test Run
    runs-on: ubuntu-20.04

    steps:

      - name: "Create a check run"
        env:
          trigger_url: '${{ secrets.MQL_MOCK_TRIGGER }}'
          branch: '${{ github.ref_name }}'
          repo: '${{ github.repository }}'
        run: |
          echo '{"branch":'$branch',"repo":'$repo'}'
          
          curl -X POST $trigger_url  \
            -H 'Content-Type: application/json' \
            -d '{"branch":'$branch',"repo":'$repo'}'