name: Auto-tag External PRs

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if PR author is external
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.pull_request.user.login;
            console.log(`Checking membership for user: ${username}`);
            
            const { data: org } = await github.rest.orgs.checkMembershipForUser({
              org: 'sublime-security',
              username: username
            }).catch((error) => {
              console.log(`Error checking membership: ${error.message}`);
              return { data: null };
            });
            
            console.log(`Membership result:`, org);
            
            if (!org || org.state !== 'active') {
              console.log('User is external, adding review-needed label');
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['review-needed']
              });
              console.log('Added review-needed label to external PR');
            } else {
              console.log('User is internal, no label added');
            }