name: Auto Add Rule ID

on:
  pull_request:
    branches: [ "**" ]

concurrency:
  group: rule-ids-${{ github.ref }}

jobs:
  rule-ids:
    name: Add Rule IDs & Validate Uniqueness
    runs-on: ubuntu-20.04

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add Rule IDs as Needed & Check for Duplicates
        run: |
          pip install -r scripts/generate-rule-ids/requirements.txt
          python scripts/generate-rule-ids/main.py

      - id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Cleanup files not related to this PR
        run: |
          git add ${{ steps.changed_files.outputs.all }}
          git checkout .
          git restore --staged

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: |
            Friendly robot here. Rule IDs allow us to track a rule even if the name or file name change. Please commit
            the suggested change.            
            
            p.s. The recommended/normal flow is just to submit a PR without `id` set and let this comment happen.
